### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Naleksuh**

### CODE REVIEW

**Comment by Naleksuh** [comment]
<noscript> is bad and doesn't work half the time. MW doesn't use it for a reason, why use it here?

Also, why not meta refresh to /web1? Or is that not part of web 1.0?

**Comment by molly** [comment]
> Also, why not meta refresh to /web1? Or is that not part of web 1.0?

Wouldn't that redirect all users to /web1, not just the no-js folks?

**Comment by Naleksuh** [comment]
Yeah, it would. I was thinking of if it was put into a <noscript> tag, not here where that isn't used.

There are other better ways to have no-js support but it involves adding a lot of unnecessary code. Not sure if that is worth the effort. Plus, the website is about web3 so it makes sense to be there, right?

**Comment by Naleksuh** [comment]
Nice steal on your GitHub username btw

**Comment by molly** [comment]
Yeah, agreed that I'm not super inclined to put a ton of work into the no-js solution. Thanks!

**Pull request merged**
